In [55]:
import main_Stuart as ms

import main_functions_Stewart_platform as mf

import numpy as np

import pandas as pd

In [68]:
#решить вопрос с инициализацией, тк нельзя в инициализации возвращать что либо.
class Dataset():

    def __init__(self,model,n):
        
        self.model = model

        self.results = np.array([])

        self.intermediate_result = np.array([])

        while n != 0:

            coordinates = (np.random.rand(3)*self.model.max_len)-self.model.min_len

            angle = ((np.pi*np.random.rand(3))/180)

            self.intermediate_result = self.model.change_of_position_upper_platform(alfa = angle[0],betta = angle[1],gamma = angle[2],\

                x = coordinates[0],y = coordinates[1],z = coordinates[2])

            self.model.len_leg()

            self.model.angle()

            if sum(self.model.test_lens) == 6 and sum(sum(self.model.test_angle)) == 12:

                self.results = np.append(self.results,(angle,coordinates,self.model.angle_lens,self.model.len))

                n-=1

            else:

                self.model.coordinates_upper_platform = mf.calculation_new_coordinates(self.model._Stuart__inv_matrix, self.model.coordinates_upper_platform).reshape(-1,3)

In [69]:
import sys

sys.path.append(sys.path[0].replace('StewartTest','StewartLibrary/'))

import main_Stuart as ms

import numpy as np

In [70]:
model = ms.Stuart(coordinates_global = [0,0,0],min_len = 100,\
     max_len = 1500, angles = 35)

Вы задали
Координаты глобальной системы:[0, 0, 0]
Минимальная и максимальная длинна ноги:(100, 1500)
Минимальный и максимальный наклон ног:(55, 125)


In [71]:
model.coordinate_lower_platform(alfa = 0, betta=0, gamma = 0,\
     x = 0, y=0, z=0, R_lower=350)

In [72]:
model.coordinate_upper_platform(alfa = 0, betta=0, gamma = 0,x = 0, y=-0, z=0, R_upper=300)

In [78]:
e  = Dataset(model,1)

/opt/anaconda3/lib/python3.6/site-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)


In [93]:
r = np.array([])
for i in e.results:
    r = np.concatenate((r,i.reshape(1,-1)))
    try:
        print(r)
    except:
        print(r)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [94]:
np.concatenate(np.array([1,2]),np.array([1,4,3,2,1]))

TypeError: only integer scalar arrays can be converted to a scalar index

In [ ]:
mf.calculation_new_coordinates(model._Stuart__inv_matrix, model.coordinates_upper_platform).reshape(-1,3)

array([[ -72.5617389 ,  163.25387512,  178.23515757],
       [-216.86764111,  -77.80561861,   73.0394967 ],
       [ -62.65724789, -323.72101602,   -2.75477712],
       [ 235.85904754, -328.57691968,   26.64660993],
       [ 380.16494975,  -87.51742594,  131.8422708 ],
       [ 225.95455653,  158.39797146,  207.63654462],
       [  81.64865432,  -82.66152228,  102.44088375]])

In [ ]:
mf.calculation_new_coordinates(model._Stuart__transform_matrix, model.coordinates_upper_platform).reshape(-1,3)

array([[ 5.01377540e+01,  1.86475934e+02,  3.00463754e+02],
       [-9.63596835e+01, -3.76127508e+01,  1.65102157e+02],
       [ 5.09135438e+01, -2.24076699e+02, -1.80420283e+01],
       [ 3.44684209e+02, -1.86451962e+02, -6.58246161e+01],
       [ 4.91181646e+02,  3.76367230e+01,  6.95369812e+01],
       [ 3.43908419e+02,  2.24100671e+02,  2.52681166e+02],
       [ 1.97410981e+02,  1.19861193e-02,  1.17319569e+02]])

In [12]:
sum(model.test_lens)

6

In [10]:
sum(sum(np.array([[ True,True],[ True,True],[True,True],[True,True],[True,True],[ True,True]])))

12

In [32]:
for i in range(100):
    print(0.01*(np.random.rand(3)*model.max_len - model.max_len/2))

[ 6.44829833 -3.96791256 -0.53006732]
[-7.35968069  0.31861087 -6.20494139]
[-1.55257527 -6.01054899 -5.18003779]
[ 1.78284415 -7.2791757  -1.95490759]
[-3.88658267  6.09218808 -0.44785305]
[-1.34608202 -1.19752681 -1.61393526]
[-1.82365912  5.06249905 -6.15176219]
[-3.90951681  0.12958049  0.30035586]
[-6.5795843  -4.69462428  5.92860127]
[ 0.50656712 -4.03326658  2.55053636]
[-5.9420488  -4.93378469  4.6603206 ]
[-3.58461202  5.38913097  6.1440472 ]
[ 5.67212409 -2.9511149  -5.35959016]
[-4.29889937  1.29676422  0.13008161]
[-0.08712495  2.42501413 -3.33822516]
[-2.19498077  3.87654629  4.57376129]
[-1.75271775  0.68909483 -7.43676262]
[7.11955347 2.7827144  0.79914212]
[ 3.86258094 -4.46907093 -0.56078454]
[-1.2093599  -3.12428089  0.13850429]
[-7.28576129  2.36028653  6.85599712]
[-0.30708687  6.33610426  1.99173166]
[ 0.82155606  6.51481593 -1.98591568]
[-4.89681606  1.29519769 -1.46319394]
[ 2.95912028 -1.58215984 -3.14122927]
[-1.09582328 -4.73654523 -1.20912242]
[ 4.36417355 -5

In [36]:
np.cos(60*np.pi/180)

0.5000000000000001