In [1]:
import sys

sys.path.append("/Users/neit1t/Documents/GitHub/Stewart_platform/StewartLibrary/")

import main_Stuart as ms

import numpy as np

Для начала нам нужно создать экземпляр класса Stuart для начала создания модели.

Stuart(): object

Stuart(coordinates_global = , min_len = , max_len = , min_angle = , max_angle = )

    Для начала создания модели по платформе Стюарта создадим экземпляр класса.
        
        Parametrs:

            coordinates_global: array (np.array,list)
                Координаты начала глобальной системы координат

            min_len: int,float
                Минимальная длинна ноги платформы Стюарта

            max_len: int,float
                Максимальная длинна ноги платформы Стюарта

            min_angle: int,float
                Минимальный угол наклона шарниров

            max_angle: int,float
                Максимальный угол наклона шарниров
            
        Returns: object
            Модель платформы Стюарта

In [2]:
model = ms.Stuart(coordinates_global = [0,0,0],min_len = 300,\
     max_len = 600, min_angle = 35, max_angle = 90)

Следующим этапом инициализации нашей платформы будет задания верхнего и нижнего основания. Зададим нижнюю платформу.

Stuart.coordinate_lower_platform(): function

Stuart.coordinate_lower_platform(alfa = , betta = , gamma = , x = , y = , z = , R_lower = )

    Создание шести точек и центра верхней платформы
        
        Parametrs:

            alfa: int,float
                Угол поворота относительно оси Ox
            
            betta: int,float
                Угол поворота относительно оси Oy

            gamma: int,float
                Угол поворота относительно оси Oz

            x: int,float
                Перемещение по оси Ox

            y: int,float
                Перемещение по оси Oy

            z: int,float
                Перемещение по оси Oz

            R_lower: int,float
                Радиус нижней платформы

        Returns: np.array
            Возвращает шесть точек нижней платформы и центр

In [3]:
model.coordinate_lower_platform(alfa = 45, betta=75, gamma = 0,\
     x = -200, y=-34, z=90, R_lower=350)

print(model.coordinates_lower_platform)

[[-109.41333421  205.05444566 -149.05444566]
 [-154.70666711  299.85757532  184.80312966]
 [-245.29333289   60.80312966  423.85757532]
 [-290.58666579 -273.05444566  329.05444566]
 [-245.29333289 -367.85757532   -4.80312966]
 [-154.70666711 -128.80312966 -243.85757532]
 [-200.          -34.           90.        ]]


Далее создадим верхнюю платформу.

Stuart.coordinate_upper_platform(): function

Stuart.coordinate_upper_platform(alfa = , betta = , gamma = , x = , y = , z = , R_upper = )

    Создание шести точек и центра верхней платформы
        
        Parametrs:

            alfa: int,float
                Угол поворота относительно оси Ox
            
            betta: int,float
                Угол поворота относительно оси Oy

            gamma: int,float
                Угол поворота относительно оси Oz

            x: int,float
                Перемещение по оси Ox

            y: int,float
                Перемещение по оси Oy

            z: int,float
                Перемещение по оси Oz

            R_upper: int,float
                Радиус верхней платформы

        Returns: np.array
            Возвращает шесть точек верхней платформы и центр

In [4]:
model.coordinate_upper_platform(alfa = 30, betta=5, gamma = 90,\
     x = 150, y=-34, z=90, R_upper=300)

print(model.coordinates_upper_platform)

[[   0.57079529  184.46331929  231.22567366]
 [-148.85840943  -47.07336141  112.64372619]
 [   0.57079529 -265.53668071  -28.58194747]
 [ 299.42920471 -252.46331929  -51.22567366]
 [ 448.85840943  -20.92663859   67.35627381]
 [ 299.42920471  197.53668071  208.58194747]
 [ 150.          -34.           90.        ]]


После создания верхнего и нижнего положения платформы мы можем посмотреть их координаты как глобальной системеме координат, так и в локальных.

Stuart.coordinates_in_sistem()

Stuart.coordinates_in_sistem(platform = , system = )

    Координаты верхнего или нижнего основания в глобальных или локальных системах координат

    Parametrs:

        platform: {'lower','upper'}
            У какой платформы хотим узнать координаты

        system: {'local','global'}
            В какой системе координат

    Returns: np.array
        Возвращает координаты платформы в выбранной нами системе координат.

In [5]:
print(model.coordinates_in_sistem(platform='lower',system='global'),\
    model.coordinates_in_sistem(platform='upper',system='local'),\
        sep = '\n')

[[-109.41333421  205.05444566 -149.05444566]
 [-154.70666711  299.85757532  184.80312966]
 [-245.29333289   60.80312966  423.85757532]
 [-290.58666579 -273.05444566  329.05444566]
 [-245.29333289 -367.85757532   -4.80312966]
 [-154.70666711 -128.80312966 -243.85757532]
 [-200.          -34.           90.        ]]
[[ 104.66583474  254.33852604  179.60104095]
 [ -11.15880687    6.76726983   55.93566384]
 [ -25.23797583 -247.5712562   214.40866209]
 [  76.50749683 -254.33852604  496.54703745]
 [ 192.33213844   -6.76726983  620.21241456]
 [ 206.4113074   247.5712562   461.73941632]
 [  90.58666579    0.          338.0740392 ]]


Мы можем перемещать и поворачивать верхнюю платформу.

Stuart.change_of_position_upper_platform()

Stuart.change_of_position_upper_platform(alfa = , betta = , gamma = , x = , y = , z = )

    Изменение положения верхней платформы
        
        Parametrs:

            alfa: int,float
                Угол поворота относительно оси Ox
            
            betta: int,float
                Угол поворота относительно оси Oy

            gamma: int,float
                Угол поворота относительно оси Oz

            x: int,float
                Перемещение по оси Ox

            y: int,float
                Перемещение по оси Oy

            z: int,float
                Перемещение по оси Oz

        Returns: np.array
            Возвращает шесть точек верхней платформы и центр

In [6]:
model.change_of_position_upper_platform(alfa= 13 , betta = -20, gamma = 10, x = 20, y = -15, z = -40)

array([[ -88.65558483,  115.64512472,  202.11189439],
       [-148.60122465,  -98.51777574,    0.76450223],
       [  73.63301501, -267.252767  , -109.41918733],
       [ 355.81289451, -221.8248578 ,  -18.25548472],
       [ 415.75853434,   -7.66195734,  183.09190745],
       [ 193.52429467,  161.07303392,  293.275597  ],
       [ 133.57865484,  -53.08986654,   91.92820484]])

После того, как мы получили новые координаты, надо проверить как изменились длинны наших ног

Stuart.len_leg()

Stuart.len_leg(test = False)

    Результат проверки по длиннам ног

    Parametrs:

        test: bool
            Массив длинн ног. Если True длинна ноги находится в допустимых значениях, иначе False.
            

    Returns: list(tuple)
    
        1D массив. 
        Длинны ног.

In [7]:
print(model.len_leg(test= True))

[ True  True  True False False  True]
[362.963785   340.78952671 508.08564515 644.80210282 656.79141248
 537.92326424]


Так как у нас 2 критерия, по которым происходит проверка, нужно проверить лежат ли наши отклоненные ноги в заданном диапазоне

Stuart.angle()

Stuart.angle()

    Результат проверки по углам наклона ног

    Parametrs:

        test: bool
            Массив наклона ног.Если True угол наклона ноги находится в допустимых значениях, иначе False.

    Returns: list(tuple)
        2D массив. (угол наклона у верхнего основания, угол наклона у нижнего основания)
        Углы наклона ног.

In [8]:
print(model.angle())

[[69.00456214 35.4859106 ]
 [84.17583872 20.20686085]
 [43.1732171  53.49068325]
 [32.45644549 66.17231156]
 [31.59696167 68.92048652]
 [39.61712077 61.85378989]]
